services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: shiftboard
      MYSQL_USER: app
      MYSQL_PASSWORD: app_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "13306:3306"

  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      FUEL_ENV: docker
      DB_HOST: db
      DB_PORT: "3306"
      DB_DATABASE: shiftboard
      DB_USERNAME: app
      DB_PASSWORD: app_pass
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    ports:
      - "8081:80"